In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import requests
import pandas as pd
import time

API_KEY = "69378d89c6133ef7fba24f43eec64f9c"

url = "https://api.themoviedb.org/3/discover/movie"

all_movies = []

for page in range(1, 562):

    params = {
        "api_key": API_KEY,
        "page": page
    }

    r = requests.get(url, params=params)

    if r.status_code != 200:
        print("ERROR:", page, r.status_code)
        print(r.text)
        break

    data = r.json()

    all_movies.extend(data["results"])

    print(f"Page {page}/561 | Movies: {len(all_movies)}")

    time.sleep(0.1)

df = pd.DataFrame(all_movies)

df.to_csv("tmdb_movies.csv", index=False)

print("DONE!")
print("Total movies:", len(df))

Page 1/561 | Movies: 20
Page 2/561 | Movies: 40
Page 3/561 | Movies: 60
Page 4/561 | Movies: 80
Page 5/561 | Movies: 100
Page 6/561 | Movies: 120
Page 7/561 | Movies: 140
Page 8/561 | Movies: 160
Page 9/561 | Movies: 180
Page 10/561 | Movies: 200
Page 11/561 | Movies: 220
Page 12/561 | Movies: 240
Page 13/561 | Movies: 260
Page 14/561 | Movies: 280
Page 15/561 | Movies: 300
Page 16/561 | Movies: 320
Page 17/561 | Movies: 340
Page 18/561 | Movies: 360
Page 19/561 | Movies: 380
Page 20/561 | Movies: 400
Page 21/561 | Movies: 420
Page 22/561 | Movies: 440
Page 23/561 | Movies: 460
Page 24/561 | Movies: 480
Page 25/561 | Movies: 500
Page 26/561 | Movies: 520
Page 27/561 | Movies: 540
Page 28/561 | Movies: 560
Page 29/561 | Movies: 580
Page 30/561 | Movies: 600
Page 31/561 | Movies: 620
Page 32/561 | Movies: 640
Page 33/561 | Movies: 660
Page 34/561 | Movies: 680
Page 35/561 | Movies: 700
Page 36/561 | Movies: 720
Page 37/561 | Movies: 740
Page 38/561 | Movies: 760
Page 39/561 | Movies: 780
Page 40/561 | Movies: 800
Page 41/561 | Movies: 820
Page 42/561 | Movies: 840
Page 43/561 | Movies: 860
Page 44/561 | Movies: 880
Page 45/561 | Movies: 900
Page 46/561 | Movies: 920
Page 47/561 | Movies: 940
Page 48/561 | Movies: 960
Page 49/561 | Movies: 980
Page 50/561 | Movies: 1000
Page 51/561 | Movies: 1020
Page 52/561 | Movies: 1040
Page 53/561 | Movies: 1060
Page 54/561 | Movies: 1080
Page 55/561 | Movies: 1100
Page 56/561 | Movies: 1120
Page 57/561 | Movies: 1140
Page 58/561 | Movies: 1160
Page 59/561 | Movies: 1180
Page 60/561 | Movies: 1200
Page 61/561 | Movies: 1220
Page 62/561 | Movies: 1240
Page 63/561 | Movies: 1260
Page 64/561 | Movies: 1280
Page 65/561 | Movies: 1300
Page 66/561 | Movies: 1320
Page 67/561 | Movies: 1340
Page 68/561 | Movies: 1360
Page 69/561 | Movies: 1380
Page 70/561 | Movies: 1400
Page 71/561 | Movies: 1420
Page 72/561 | Movies: 1440
Page 73/561 | Movies: 1460
Page 74/561 | Movies: 1480
Page 75/561 | Movies: 1500
Page 76/561 | Movies: 1520
Page 77/561 | Movies: 1540
Page 78/561 | Movies: 1560
Page 79/561 | Movies: 1580
Page 80/561 | Movies: 1600
Page 81/561 | Movies: 1620
Page 82/561 | Movies: 1640
Page 83/561 | Movies: 1660
Page 84/561 | Movies: 1680
Page 85/561 | Movies: 1700
Page 86/561 | Movies: 1720
Page 87/561 | Movies: 1740
Page 88/561 | Movies: 1760
Page 89/561 | Movies: 1780
Page 90/561 | Movies: 1800
Page 91/561 | Movies: 1820
Page 92/561 | Movies: 1840
Page 93/561 | Movies: 1860
Page 94/561 | Movies: 1880
Page 95/561 | Movies: 1900
Page 96/561 | Movies: 1920
Page 97/561 | Movies: 1940
Page 98/561 | Movies: 1960
Page 99/561 | Movies: 1980
Page 100/561 | Movies: 2000
Page 101/561 | Movies: 2020
Page 102/561 | Movies: 2040
Page 103/561 | Movies: 2060
Page 104/561 | Movies: 2080
Page 105/561 | Movies: 2100
Page 106/561 | Movies: 2120
Page 107/561 | Movies: 2140
Page 108/561 | Movies: 2160
Page 109/561 | Movies: 2180
Page 110/561 | Movies: 2200
Page 111/561 | Movies: 2220
Page 112/561 | Movies: 2240
Page 113/561 | Movies: 2260
Page 114/561 | Movies: 2280
Page 115/561 | Movies: 2300
Page 116/561 | Movies: 2320
Page 117/561 | Movies: 2340
Page 118/561 | Movies: 2360
Page 119/561 | Movies: 2380
Page 120/561 | Movies: 2400
Page 121/561 | Movies: 2420
Page 122/561 | Movies: 2440
Page 123/561 | Movies: 2460
Page 124/561 | Movies: 2480
Page 125/561 | Movies: 2500
Page 126/561 | Movies: 2520
Page 127/561 | Movies: 2540
Page 128/561 | Movies: 2560
Page 129/561 | Movies: 2580
Page 130/561 | Movies: 2600
Page 131/561 | Movies: 2620
Page 132/561 | Movies: 2640
Page 133/561 | Movies: 2660
Page 134/561 | Movies: 2680
Page 135/561 | Movies: 2700
Page 136/561 | Movies: 2720
Page 137/561 | Movies: 2740
Page 138/561 | Movies: 2760
Page 139/561 | Movies: 2780
Page 140/561 | Movies: 2800
Page 141/561 | Movies: 2820
Page 142/561 | Movies: 2840
Page 143/561 | Movies: 2860
Page 144/561 | Movies: 2880
Page 145/561 | Movies: 2900
Page 146/561 | Movies: 2920
Page 147/561 | Movies: 2940
Page 148/561 | Movies: 2960
Page 149/561 | Movies: 2980
Page 150/561 | Movies: 3000
Page 151/561 | Movies: 3020
Page 152/561 | Movies: 3040
Page 153/561 | Movies: 3060
Page 154/561 | Movies: 3080
Page 155/561 | Movies: 3100
Page 156/561 | Movies: 3120
Page 157/561 | Movies: 3140
Page 158/561 | Movies: 3160
Page 159/561 | Movies: 3180
Page 160/561 | Movies: 3200
Page 161/561 | Movies: 3220
Page 162/561 | Movies: 3240
Page 163/561 | Movies: 3260
Page 164/561 | Movies: 3280
Page 165/561 | Movies: 3300
Page 166/561 | Movies: 3320
Page 167/561 | Movies: 3340
Page 168/561 | Movies: 3360
Page 169/561 | Movies: 3380
Page 170/561 | Movies: 3400
Page 171/561 | Movies: 3420
Page 172/561 | Movies: 3440
Page 173/561 | Movies: 3460
Page 174/561 | Movies: 3480
Page 175/561 | Movies: 3500
Page 176/561 | Movies: 3520
Page 177/561 | Movies: 3540
Page 178/561 | Movies: 3560
Page 179/561 | Movies: 3580
Page 180/561 | Movies: 3600
Page 181/561 | Movies: 3620
Page 182/561 | Movies: 3640
Page 183/561 | Movies: 3660
Page 184/561 | Movies: 3680
Page 185/561 | Movies: 3700
Page 186/561 | Movies: 3720
Page 187/561 | Movies: 3740
Page 188/561 | Movies: 3760
Page 189/561 | Movies: 3780
Page 190/561 | Movies: 3800
Page 191/561 | Movies: 3820
Page 192/561 | Movies: 3840
Page 193/561 | Movies: 3860
Page 194/561 | Movies: 3880
Page 195/561 | Movies: 3900
Page 196/561 | Movies: 3920
Page 197/561 | Movies: 3940
Page 198/561 | Movies: 3960
Page 199/561 | Movies: 3980
Page 200/561 | Movies: 4000
Page 201/561 | Movies: 4020
Page 202/561 | Movies: 4040
Page 203/561 | Movies: 4060
Page 204/561 | Movies: 4080
Page 205/561 | Movies: 4100
Page 206/561 | Movies: 4120
Page 207/561 | Movies: 4140
Page 208/561 | Movies: 4160
Page 209/561 | Movies: 4180
Page 210/561 | Movies: 4200
Page 211/561 | Movies: 4220
Page 212/561 | Movies: 4240
Page 213/561 | Movies: 4260
Page 214/561 | Movies: 4280
Page 215/561 | Movies: 4300
Page 216/561 | Movies: 4320
Page 217/561 | Movies: 4340
Page 218/561 | Movies: 4360
Page 219/561 | Movies: 4380
Page 220/561 | Movies: 4400
Page 221/561 | Movies: 4420
Page 222/561 | Movies: 4440
Page 223/561 | Movies: 4460
Page 224/561 | Movies: 4480
Page 225/561 | Movies: 4500
Page 226/561 | Movies: 4520
Page 227/561 | Movies: 4540
Page 228/561 | Movies: 4560
Page 229/561 | Movies: 4580
Page 230/561 | Movies: 4600
Page 231/561 | Movies: 4620
Page 232/561 | Movies: 4640
Page 233/561 | Movies: 4660
Page 234/561 | Movies: 4680
Page 235/561 | Movies: 4700
Page 236/561 | Movies: 4720
Page 237/561 | Movies: 4740
Page 238/561 | Movies: 4760
Page 239/561 | Movies: 4780
Page 240/561 | Movies: 4800
Page 241/561 | Movies: 4820
Page 242/561 | Movies: 4840
Page 243/561 | Movies: 4860
Page 244/561 | Movies: 4880
Page 245/561 | Movies: 4900
Page 246/561 | Movies: 4920
Page 247/561 | Movies: 4940
Page 248/561 | Movies: 4960
Page 249/561 | Movies: 4980
Page 250/561 | Movies: 5000
Page 251/561 | Movies: 5020
Page 252/561 | Movies: 5040
Page 253/561 | Movies: 5060
Page 254/561 | Movies: 5080
Page 255/561 | Movies: 5100
Page 256/561 | Movies: 5120
Page 257/561 | Movies: 5140
Page 258/561 | Movies: 5160
Page 259/561 | Movies: 5180
Page 260/561 | Movies: 5200
Page 261/561 | Movies: 5220
Page 262/561 | Movies: 5240
Page 263/561 | Movies: 5260
Page 264/561 | Movies: 5280
Page 265/561 | Movies: 5300
Page 266/561 | Movies: 5320
Page 267/561 | Movies: 5340
Page 268/561 | Movies: 5360
Page 269/561 | Movies: 5380
Page 270/561 | Movies: 5400
Page 271/561 | Movies: 5420
Page 272/561 | Movies: 5440
Page 273/561 | Movies: 5460
Page 274/561 | Movies: 5480
Page 275/561 | Movies: 5500
Page 276/561 | Movies: 5520
Page 277/561 | Movies: 5540
Page 278/561 | Movies: 5560
Page 279/561 | Movies: 5580
Page 280/561 | Movies: 5600
Page 281/561 | Movies: 5620
Page 282/561 | Movies: 5640
Page 283/561 | Movies: 5660
Page 284/561 | Movies: 5680
Page 285/561 | Movies: 5700
Page 286/561 | Movies: 5720
Page 287/561 | Movies: 5740
Page 288/561 | Movies: 5760
Page 289/561 | Movies: 5780
Page 290/561 | Movies: 5800
Page 291/561 | Movies: 5820
Page 292/561 | Movies: 5840
Page 293/561 | Movies: 5860
Page 294/561 | Movies: 5880
Page 295/561 | Movies: 5900
Page 296/561 | Movies: 5920
Page 297/561 | Movies: 5940
Page 298/561 | Movies: 5960
Page 299/561 | Movies: 5980
Page 300/561 | Movies: 6000
Page 301/561 | Movies: 6020
Page 302/561 | Movies: 6040
Page 303/561 | Movies: 6060
Page 304/561 | Movies: 6080
Page 305/561 | Movies: 6100
Page 306/561 | Movies: 6120
Page 307/561 | Movies: 6140
Page 308/561 | Movies: 6160
Page 309/561 | Movies: 6180
Page 310/561 | Movies: 6200
Page 311/561 | Movies: 6220
Page 312/561 | Movies: 6240
Page 313/561 | Movies: 6260
Page 314/561 | Movies: 6280
Page 315/561 | Movies: 6300
Page 316/561 | Movies: 6320
Page 317/561 | Movies: 6340
Page 318/561 | Movies: 6360
Page 319/561 | Movies: 6380
Page 320/561 | Movies: 6400
Page 321/561 | Movies: 6420
Page 322/561 | Movies: 6440
Page 323/561 | Movies: 6460
Page 324/561 | Movies: 6480
Page 325/561 | Movies: 6500
Page 326/561 | Movies: 6520
Page 327/561 | Movies: 6540
Page 328/561 | Movies: 6560
Page 329/561 | Movies: 6580
Page 330/561 | Movies: 6600
Page 331/561 | Movies: 6620
Page 332/561 | Movies: 6640
Page 333/561 | Movies: 6660
Page 334/561 | Movies: 6680
Page 335/561 | Movies: 6700
Page 336/561 | Movies: 6720
Page 337/561 | Movies: 6740
Page 338/561 | Movies: 6760
Page 339/561 | Movies: 6780
Page 340/561 | Movies: 6800
Page 341/561 | Movies: 6820
Page 342/561 | Movies: 6840
Page 343/561 | Movies: 6860
Page 344/561 | Movies: 6880
Page 345/561 | Movies: 6900
Page 346/561 | Movies: 6920
Page 347/561 | Movies: 6940
Page 348/561 | Movies: 6960
Page 349/561 | Movies: 6980
Page 350/561 | Movies: 7000
Page 351/561 | Movies: 7020
Page 352/561 | Movies: 7040
Page 353/561 | Movies: 7060
Page 354/561 | Movies: 7080
Page 355/561 | Movies: 7100
Page 356/561 | Movies: 7120
Page 357/561 | Movies: 7140
Page 358/561 | Movies: 7160
Page 359/561 | Movies: 7180
Page 360/561 | Movies: 7200
Page 361/561 | Movies: 7220
Page 362/561 | Movies: 7240
Page 363/561 | Movies: 7260
Page 364/561 | Movies: 7280
Page 365/561 | Movies: 7300
Page 366/561 | Movies: 7320
Page 367/561 | Movies: 7340
Page 368/561 | Movies: 7360
Page 369/561 | Movies: 7380
Page 370/561 | Movies: 7400
Page 371/561 | Movies: 7420
Page 372/561 | Movies: 7440
Page 373/561 | Movies: 7460
Page 374/561 | Movies: 7480
Page 375/561 | Movies: 7500
Page 376/561 | Movies: 7520
Page 377/561 | Movies: 7540
Page 378/561 | Movies: 7560
Page 379/561 | Movies: 7580
Page 380/561 | Movies: 7600
Page 381/561 | Movies: 7620
Page 382/561 | Movies: 7640
Page 383/561 | Movies: 7660
Page 384/561 | Movies: 7680
Page 385/561 | Movies: 7700
Page 386/561 | Movies: 7720
Page 387/561 | Movies: 7740
Page 388/561 | Movies: 7760
Page 389/561 | Movies: 7780
Page 390/561 | Movies: 7800
Page 391/561 | Movies: 7820
Page 392/561 | Movies: 7840
Page 393/561 | Movies: 7860
Page 394/561 | Movies: 7880
Page 395/561 | Movies: 7900
Page 396/561 | Movies: 7920
Page 397/561 | Movies: 7940
Page 398/561 | Movies: 7960
Page 399/561 | Movies: 7980
Page 400/561 | Movies: 8000
Page 401/561 | Movies: 8020
Page 402/561 | Movies: 8040
Page 403/561 | Movies: 8060
Page 404/561 | Movies: 8080
Page 405/561 | Movies: 8100
Page 406/561 | Movies: 8120
Page 407/561 | Movies: 8140
Page 408/561 | Movies: 8160
Page 409/561 | Movies: 8180
Page 410/561 | Movies: 8200
Page 411/561 | Movies: 8220
Page 412/561 | Movies: 8240
Page 413/561 | Movies: 8260
Page 414/561 | Movies: 8280
Page 415/561 | Movies: 8300
Page 416/561 | Movies: 8320
Page 417/561 | Movies: 8340
Page 418/561 | Movies: 8360
Page 419/561 | Movies: 8380
Page 420/561 | Movies: 8400
Page 421/561 | Movies: 8420
Page 422/561 | Movies: 8440
Page 423/561 | Movies: 8460
Page 424/561 | Movies: 8480
Page 425/561 | Movies: 8500
Page 426/561 | Movies: 8520
Page 427/561 | Movies: 8540
Page 428/561 | Movies: 8560
Page 429/561 | Movies: 8580
Page 430/561 | Movies: 8600
Page 431/561 | Movies: 8620
Page 432/561 | Movies: 8640
Page 433/561 | Movies: 8660
Page 434/561 | Movies: 8680
Page 435/561 | Movies: 8700
Page 436/561 | Movies: 8720
Page 437/561 | Movies: 8740
Page 438/561 | Movies: 8760
Page 439/561 | Movies: 8780
Page 440/561 | Movies: 8800
Page 441/561 | Movies: 8820
Page 442/561 | Movies: 8840
Page 443/561 | Movies: 8860
Page 444/561 | Movies: 8880
Page 445/561 | Movies: 8900
Page 446/561 | Movies: 8920
Page 447/561 | Movies: 8940
Page 448/561 | Movies: 8960
Page 449/561 | Movies: 8980
Page 450/561 | Movies: 9000
Page 451/561 | Movies: 9020
Page 452/561 | Movies: 9040
Page 453/561 | Movies: 9060
Page 454/561 | Movies: 9080
Page 455/561 | Movies: 9100
Page 456/561 | Movies: 9120
Page 457/561 | Movies: 9140
Page 458/561 | Movies: 9160
Page 459/561 | Movies: 9180
Page 460/561 | Movies: 9200
Page 461/561 | Movies: 9220
Page 462/561 | Movies: 9240
Page 463/561 | Movies: 9260
Page 464/561 | Movies: 9280
Page 465/561 | Movies: 9300
Page 466/561 | Movies: 9320
Page 467/561 | Movies: 9340
Page 468/561 | Movies: 9360
Page 469/561 | Movies: 9380
Page 470/561 | Movies: 9400
Page 471/561 | Movies: 9420
Page 472/561 | Movies: 9440
Page 473/561 | Movies: 9460
Page 474/561 | Movies: 9480
Page 475/561 | Movies: 9500
Page 476/561 | Movies: 9520
Page 477/561 | Movies: 9540
Page 478/561 | Movies: 9560
Page 479/561 | Movies: 9580
Page 480/561 | Movies: 9600
Page 481/561 | Movies: 9620
Page 482/561 | Movies: 9640
Page 483/561 | Movies: 9660
Page 484/561 | Movies: 9680
Page 485/561 | Movies: 9700
Page 486/561 | Movies: 9720
Page 487/561 | Movies: 9740
Page 488/561 | Movies: 9760
Page 489/561 | Movies: 9780
Page 490/561 | Movies: 9800
Page 491/561 | Movies: 9820
Page 492/561 | Movies: 9840
Page 493/561 | Movies: 9860
Page 494/561 | Movies: 9880
Page 495/561 | Movies: 9900
Page 496/561 | Movies: 9920
Page 497/561 | Movies: 9940
Page 498/561 | Movies: 9960
Page 499/561 | Movies: 9980
Page 500/561 | Movies: 10000
ERROR: 501 400
{"success":false,"status_code":22,"status_message":"Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."}
DONE!
Total movies: 10000

In [3]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,691.7198,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.848,2702
1,False,/7GOW6jod9lLurW5utokAatxg7ql.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,539.7588,/vhv7lBWYM0DUuNU2a0V7Rhq21dD.jpg,2026-08-20,False,False,7.587,399
2,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,399.4395,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.094,796
3,False,/iuylzRSllrGn7YB322kwKoOVMcq.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",383.4669,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.009,3726
4,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,"[878, 9648, 53]",1101383,The End of Oak Street,en,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,367.9096,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,2026-08-12,False,False,6.736,799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,/ca0a79cbCGWJdan3SEBKkQBSwKi.jpg,"[18, 36, 10752]",76758,The Flowers of War,zh,金陵十三釵,A Westerner finds refuge with a group of women...,5.4978,/7NVgVX663tdareijAiv0eLiLn6d.jpg,2011-12-15,False,False,7.424,930
9996,False,None,[],410017,A vírus,en,A vírus,In the life of a young virologist appears a di...,4.5480,None,2005-01-01,False,False,5.800,5
9997,False,/rHQgHQ3YIYcWe3FI0sl7oYohoh1.jpg,"[35, 18]",219811,English Education,fr,Éducation anglaise,"After losing both her parents, young Sylvie is...",4.0322,/xWglrXbQhhEdg1nGbsOLNyFHngX.jpg,1983-06-07,False,False,4.813,16
9998,False,None,[99],653399,Haunted Palace,en,Haunted Palace,This short film documentary features Shaw Desm...,4.4106,/9MyqDd3ukNWekfCnFTYD7y8xmmC.jpg,1949-01-01,False,False,0.000,1
9999,False,/9ewYb0LIBJNds8ZMoobKYUd647g.jpg,"[35, 18]",1120911,Saturday Night,en,Saturday Night,"At 11:30pm on October 11, 1975, a ferocious tr...",4.4829,/oCf5O6uxooTvRwKVnLHwGqZUifq.jpg,2024-09-27,False,False,6.652,402

In [4]:
df.head(1)

# Drop unneeded columns safely (ignoring any that don't exist)
columns_to_drop = ['softcore', 'backdrop_path', 'poster_path', 'adult', 'video', 'genre_ids']
df.drop(columns=columns_to_drop, errors='ignore', inplace=True)

# Verify remaining columns
print(df.columns.tolist())

['id', 'title', 'original_language', 'original_title', 'overview', 'popularity', 'release_date', 'vote_average', 'vote_count']

In [5]:
df.shape

(10000, 9)

# lower casing

In [6]:
# Convert every string/object column in df at once
text_cols = df.select_dtypes(include=['object', 'string']).columns
df[text_cols] = df[text_cols].apply(lambda x: x.str.lower())

In [7]:
df

,id,title,original_language,original_title,overview,popularity,release_date,vote_average,vote_count
0,969681,spider-man: brand new day,en,spider-man: brand new day,fighting crime full-time as spider-man in a wo...,691.7198,2026-07-29,7.848,2702
1,1204680,coyote vs. acme,en,coyote vs. acme,after acme products fail him one too many time...,539.7588,2026-08-20,7.587,399
2,1375646,colony,ko,군체,professor se-jeong is thrust into a bloody nig...,399.4395,2026-05-21,8.094,796
3,1368337,the odyssey,en,the odyssey,"odysseus, the legendary king of ithaca, embark...",383.4669,2026-07-15,8.009,3726
4,1101383,the end of oak street,en,the end of oak street,after a mysterious cosmic event rips oak stree...,367.9096,2026-08-12,6.736,799
...,...,...,...,...,...,...,...,...,...
9995,76758,the flowers of war,zh,金陵十三釵,a westerner finds refuge with a group of women...,5.4978,2011-12-15,7.424,930
9996,410017,a vírus,en,a vírus,in the life of a young virologist appears a di...,4.5480,2005-01-01,5.800,5
9997,219811,english education,fr,éducation anglaise,"after losing both her parents, young sylvie is...",4.0322,1983-06-07,4.813,16
9998,653399,haunted palace,en,haunted palace,this short film documentary features shaw desm...,4.4106,1949-01-01,0.000,1
9999,1120911,saturday night,en,saturday night,"at 11:30pm on october 11, 1975, a ferocious tr...",4.4829,2024-09-27,6.652,402

**removing the html tags if any**

In [8]:
# Regex pattern to match HTML tags
html_pattern = r'<[^>]+>'

# Clean HTML tags from all text/string columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    
    df[col] = df[col].astype(str).str.replace(html_pattern, '', regex=True)

*removing url if any*

In [9]:
# Regex pattern to match URLs
url_pattern = r'https?://\S+|www\.\S+'

# Clean URLs from all text/string columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).str.replace(url_pattern, '', regex=True)

> removing punctuations if any

In [10]:
import string

# Create a regex pattern to match punctuation characters
punc_pattern = f"[{string.punctuation}]"

# Clean punctuation from all text/string columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).str.replace(punc_pattern, '', regex=True)

### chat word treatment

In [11]:
# Dictionary of common chat slangs/abbreviations
chat_words = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "G2G": "Got To Go",
    "GN": "Good Night",
    "GR8": "Great",
    "HAND": "Have A Nice Day",
    "IC": "I See",
    "IDK": "I Don't Know",
    "IMHO": "In My Humble Opinion",
    "IMO": "In My Opinion",
    "IMO": "In My Opinion",
    "LOL": "Laughing Out Loud",
    "NP": "No Problem",
    "OMG": "Oh My God",
    "ROFL": "Rolling On The Floor Laughing",
    "TBH": "To Be Honest",
    "THX": "Thanks",
    "TY": "Thank You",
}

# Function to expand chat words
def chat_conversion(text):
    new_text = []
    for word in text.split():
        # Check if uppercase word is in dictionary
        if word.upper() in chat_words:
            new_text.append(chat_words[word.upper()])
        else:
            new_text.append(word)
    return " ".join(new_text)

# Apply to overview or text columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).apply(chat_conversion)

In [12]:
import nltk
from nltk.corpus import stopwords

# Download stop words list
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Function to remove stop words
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in stop_words])

# Apply to overview or all text columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (2.15.0)

In [14]:
import emoji

# Function to demojize text
def convert_emojis(text):
    return emoji.demojize(text)

# Apply to text columns
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).apply(convert_emojis)

In [15]:
import spacy

nlp = spacy.load('en_core_web_sm')

# Function to tokenize via spaCy
def spacy_tokenize(text):
    doc = nlp(text)
    return [token.text for token in doc]

df['overview_tokens'] = df['overview'].astype(str).apply(spacy_tokenize)

In [16]:
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem_text(text):
    return " ".join([ps.stem(word) for word in text.split()])

# Apply to overview column
df['overview_stemmed'] = df['overview'].astype(str).apply(stem_text)

In [17]:
import spacy

nlp = spacy.load('en_core_web_sm')

def spacy_lemmatize(text):
    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc])

df['overview_lemmatized'] = df['overview'].astype(str).apply(spacy_lemmatize)