<a href="https://colab.research.google.com/github/Rubal-code/Machine-Learning/blob/main/only_bow_quora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/train.csv',on_bad_lines="skip")
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [5]:
new_df = df.sample(30000)

In [6]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [7]:
new_df.duplicated().sum()

np.int64(0)

In [8]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
328784,What are the main imports and exports of Venez...,What are the main imports and exports of Venez...
43671,How is energy transferred from Earth's surface...,How is the atmosphere of Mars different from t...
76137,Falklands War (1982): Why did Argentina dare t...,Why did Argentina declare war on Britain?
93324,How do I get more traffic for my site?,How do i get traffic for website?
363572,What are some of the best mobile phones gadgets?,What are the best handheld gadgets ever?

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [11]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
328784,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43671,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93324,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
363572,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210713,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192741,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
368981,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
356269,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [13]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
328784,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43671,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
93324,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
363572,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7441666666666666

In [16]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7335