In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('play_tennis.csv')
df.drop(columns=['day'],inplace=True)

In [5]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [6]:
# problem 1

# outlook = sunny, ,temp= hot, humidity = high, wind=weak

# play or not?

In [7]:
# solution

# P(play=yes|sunny,hot,high,weak)=P(sunny|yes)*P(hot|yes)*P(high|yes)*P(weak|yes)

# P(play=no|sunny,hot,high,weak)=P(sunny|no)*P(hot|no)*P(high|no)*P(weak|no)

In [8]:
# problem 2

# outlook = overcast, ,temp= cold, humidity = low, wind=weak

# play or not?

In [10]:
# solution
# P(play=yes|overcast,cold,low,weak)=P(overcast|yes)*P(cold|yes)*P(low|yes)*P(weak|yes)
# P(play=no|overcast,cold,low,weak)=P(overcast|no)*P(cold|no)*P(low|no)*P(weak|no)

# compare and decide with maximum posterior probability rule

In [11]:
# training

# lookup table 

# testing

In [12]:
# P(yes)
# P(no)

In [13]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [14]:
py=(9/14)
pn=(5/14)

In [15]:
print(py,pn)

0.6428571428571429 0.35714285714285715

In [19]:
# outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [20]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [21]:
# temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [22]:
pcn=1/5
phn=2/5
pmn=2/5

pcy=3/9
phy=2/9
pmy=4/9

In [23]:
# humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [24]:
phn=4/5
pnn=1/5

phy=3/9
pny=6/9

In [25]:
# wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [26]:
psn=3/5
pwn=2/5

psy=3/9
pwy=6/9

In [ ]:
# py* poy*pmy*psy*pwy